// Source
#include "localization.h"

// Private

// Public
const Word localization_IT = {
    .serialMessage_programStarted = "Program started.",
    .serialMessage_led1On = "LED1: On.",
    .serialMessage_led1Off = "LED1: Off.",
    .genericError = "Unknown error.",
    .uartError_bufferOverflow = "UART error - Buffer overflow.",
    .uartError_generalFailure = "UART error - General failure.",
    .uartInfo_unknownCommand = "UART info - Unknown command.",
    .sdSpiInfo_spaceTotal = "SD CARD info - Space total: ",
    .sdSpiInfo_spaceFree = "SD CARD info - Space free: ",
    .sdSpiInfo_spaceUsed = "SD CARD info - Space used: ",
    .sdSpiInfo_data = "SD CARD info - Data: ",
    .sdSpiError_mount = "SD SPI error - f_mount() - ",
    .sdSpiError_open = "SD SPI error - f_open() - ",
    .sdSpiError_getfree = "SD SPI error - f_getfree() - ",
    .sdSpiError_lseek = "SD SPI error - f_lseek() - ",
    .sdSpiError_write = "SD SPI error - f_write() - ",
    .sdSpiError_read = "SD SPI error - f_read() - ",
    .sdSpiError_open_dir = "SD SPI error - f_opendir() - ",
    .sdSpiError_unlink = "SD SPI error - f_unlink() - ",
    .sdSpiError_code1 = "Low level disk I/O layer.",
    .sdSpiError_code2 = "Assertion.",
    .sdSpiError_code3 = "Physical drive not work.",
    .sdSpiError_code4 = "File not found.",
    .sdSpiError_code5 = "Path not found.",
    .sdSpiError_code6 = "Path invalid format.",
    .sdSpiError_code7 = "Access denied.",
    .sdSpiError_code8 = "Already exists.",
    .sdSpiError_code9 = "Invalid file or directory.",
    .sdSpiError_code10 = "Disk write-protected.",
    .sdSpiError_code11 = "Invalid drive number.",
    .sdSpiError_code12 = "Drive not mounted.",
    .sdSpiError_code13 = "Drive not valid volume.",
    .sdSpiError_code14 = "Parameter error.",
    .sdSpiError_code15 = "Timeout.",
    .sdSpiError_code16 = "Locked by another operation.",
    .sdSpiError_code17 = "Not enough memory.",
    .sdSpiError_code18 = "Too many opened files.",
    .sdSpiError_code19 = "Invalid parameter."};
